### ISSUE TITLE
Badly packaged error

### ISSUE THREAD

**Issue by Naveenbc** [brentmiller/ng-icon-sidebar#3]
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by brentmiller** [comment]
Thank you for bringing up this issue, @Naveenbc. I'm happy to take a look.

This issue's title mentions an error, so my first step in troubleshooting is to recreate the error. Is this a compiler error or warning which you experience at build time? If so, could you describe how to recreate the error and provide the error message?

I ran the tasks `ng build`, `ng lint`, and `ng test` on this project and didn't see any errors or warnings which deal with packaging. Thus I need a bit more information from you before I can move forward.

**Comment by brentmiller** [comment]
Unfortunately, I am unable to recreate the issue which @Naveenbc observed. Thus I'm closing this issue. If anyone can provide further information, I will happily open it again.
